# Generated by Django 4.1 on 2022-10-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlog', '0003_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
