# Generated by Django 4.1 on 2022-10-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlog', '0005_post_author_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_blog_pic.png', null=True, upload_to='blog_pics'),
        ),
    ]
