# Generated by Django 4.1.1 on 2022-10-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlog', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
