# Generated by Django 4.1.1 on 2022-10-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlog', '0009_tag_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='created_date',
        ),
    ]
