# Generated by Django 4.1.1 on 2022-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlog', '0012_comment_delete_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ProyectoBlog.tag'),
        ),
    ]
