# Generated by Django 4.1.1 on 2022-10-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlog', '0013_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
